# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Manual

on:
  workflow_dispatch:
    inputs: 
      environment:
        required: true
        type: choice
        options:
          - Dev
          - Prod
      buildArtifact:
        required: true
        type: string

jobs:
  DevApproval:
    name: Approve Dev deployment
    environment: Dev-Review
    if: ${{ inputs.environment != '' && inputs.environment == 'Dev' }}
    runs-on: ubuntu-latest
    steps:
      - run: "echo Approving Dev Environment deployment"
    
  BuildFromDevEnv:
    name: Build From Dev Env
    environment: Dev
    runs-on: ubuntu-latest
    needs: [DevApproval]
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: website.${{ inputs.buildArtifact }}
          github_token: ${{ secrets.GH_TOKEN }}
          
  ProdApproval:
    name: Approve Prod deployment
    environment: Prod-Review
    if: ${{ inputs.environment != '' && inputs.environment == 'Prod' }}
    runs-on: ubuntu-latest
    steps:
      - run: "echo Approving Dev Environment deployment"

  BuildFromProdEnv:
    name: Build From Prod Env
    environment: Prod
    runs-on: ubuntu-latest
    needs: [ ProdApproval ]
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: website.${{ inputs.buildArtifact }}
          github_token: ${{ secrets.GH_TOKEN }}