# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths:
      - .github/workflows/build-publish.yml
      - AzureDevOpsMigrationTest/**
  
  workflow_dispatch:
    inputs: 
      environment:
        required: false
        type: choice
        options:
          - Dev
          - Prod

jobs:
  buildBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Publish
        run: dotnet publish --no-build AzureDevOpsMigrationTest/AzureDevOpsMigrationTest.csproj -c Release -o ${{env.DOTNET_ROOT}}/website
        
      - name: Check environment
        run: echo ${{ inputs.environment }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: website.${{ github.run_number }}
          path: ${{env.DOTNET_ROOT}}/website/**
          if-no-files-found: error
             
  DevApproval:
    name: Approve Dev deployment
    environment: Dev-Review
    if: ${{ (inputs.environment != '' && inputs.environment == 'Dev') || (github.ref == 'refs/heads/master' && github.event_name != 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    needs: [buildBranch]
    steps:
      - run: "echo Approving Dev Environment deployment"
    
  BuildFromDevEnv:
    name: Build From Dev Env
    environment: Dev
    runs-on: ubuntu-latest
    needs: [DevApproval]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: website.${{ github.run_number }}
          
  ProdApproval:
    name: Approve Prod deployment
    environment: Prod-Review
    if: ${{ (inputs.environment != '' && inputs.environment == 'Prod') || (github.ref == 'refs/heads/master' && github.event_name != 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    needs: [ buildBranch ]
    steps:
      - run: "echo Approving Dev Environment deployment"

  BuildFromProdEnv:
    name: Build From Prod Env
    environment: Prod
    runs-on: ubuntu-latest
    needs: [ ProdApproval ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: website.${{ github.run_number }}