name: Automated Deployment

on:
  push:
    paths:
      - .github/workflows/build-publish.yml
      - AzureDevOpsMigrationTest/**
      
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - Dev
          - Prod
      buildArtifact:
        required: true
        type: string

jobs:
  buildBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ inputs.buildArtifact == '' }}
        
      - name: Setup .NET
        if: ${{ inputs.buildArtifact == '' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore
        if: ${{ inputs.buildArtifact == '' }}
        
      - name: Build
        run: dotnet build --no-restore -c Release
        if: ${{ inputs.buildArtifact == '' }}
        
      - name: Publish
        run: dotnet publish --no-build AzureDevOpsMigrationTest/AzureDevOpsMigrationTest.csproj -c Release -o ${{env.DOTNET_ROOT}}/website
        if: ${{ inputs.buildArtifact == '' }}
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        if: ${{ inputs.buildArtifact == '' }}
        with:
          name: website.${{ github.run_number }}
          path: ${{env.DOTNET_ROOT}}/website/**
          if-no-files-found: error
             
  DevApproval:
    name: Approve Dev deployment
    environment: Dev-Review
    if: ${{ (inputs.environment != '' && inputs.environment == 'Dev') || (github.ref == 'refs/heads/master' && github.event_name != 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    needs: [buildBranch]
    steps:
      - run: "echo Approving Dev Environment deployment"
    
  BuildFromDevEnv:
    name: Build From Dev Env
    environment: Dev
    runs-on: ubuntu-latest
    needs: [DevApproval]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: website.${{ inputs.buildArtifact || github.run_number }}
          
  ProdApproval:
    name: Approve Prod deployment
    environment: Prod-Review
    if: ${{ (inputs.environment != '' && inputs.environment == 'Prod') || (github.ref == 'refs/heads/master' && github.event_name != 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    needs: [ BuildFromDevEnv ]
    steps:
      - run: "echo Approving Dev Environment deployment"

  BuildFromProdEnv:
    name: Build From Prod Env
    environment: Prod
    runs-on: ubuntu-latest
    needs: [ ProdApproval ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: website.${{ inputs.buildArtifact || github.run_number }}